

module Abstracks where

-- Haskell module generated by the BNF converter

data TrackBlock =
   PTrack String String [String] Integer Integer [Integer] String
  deriving (Eq,Ord,Show,Read)

data ReleaseBlock =
   PRelease String Integer String [String]
  deriving (Eq,Ord,Show,Read)

data CrateBlock =
   PCrate String [TrackBlock] [ReleaseBlock]
  deriving (Eq,Ord,Show,Read)

