{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Printtracks where

-- pretty-printer generated by the BNF converter

import Abstracks
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)
  prtList es = case es of
   [] -> (concatD [])
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])


instance Print Double where
  prt _ x = doc (shows x)




instance Print TrackBlock where
  prt i e = case e of
   PTrack str0 str1 strs n2 n ns str -> prPrec i 0 (concatD [doc (showString "track") , doc (showString "{") , doc (showString "title") , doc (showString "=") , prt 0 str0 , doc (showString ",") , doc (showString "location") , doc (showString "=") , prt 0 str1 , doc (showString ",") , doc (showString "artists") , doc (showString "=") , prt 0 strs , doc (showString ",") , doc (showString "bpm") , doc (showString "=") , prt 0 n2 , doc (showString ",") , doc (showString "duration") , doc (showString "=") , prt 0 n , doc (showString ",") , doc (showString "cues") , doc (showString "=") , prt 0 ns , doc (showString ",") , doc (showString "genre") , doc (showString "=") , prt 0 str , doc (showString "}")])

  prtList es = case es of
   [] -> (concatD [])
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print ReleaseBlock where
  prt i e = case e of
   PRelease str0 n str strs -> prPrec i 0 (concatD [doc (showString "release") , doc (showString "{") , doc (showString "title") , doc (showString "=") , prt 0 str0 , doc (showString ",") , doc (showString "year") , doc (showString "=") , prt 0 n , doc (showString ",") , doc (showString "label") , doc (showString "=") , prt 0 str , doc (showString ",") , doc (showString "tracks") , doc (showString "=") , prt 0 strs , doc (showString "}")])

  prtList es = case es of
   [] -> (concatD [])
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print CrateBlock where
  prt i e = case e of
   PCrate str trackblocks releaseblocks -> prPrec i 0 (concatD [doc (showString "crate") , doc (showString "{") , doc (showString "title") , doc (showString "=") , prt 0 str , doc (showString ",") , doc (showString "tracks") , doc (showString "=") , prt 0 trackblocks , doc (showString ",") , doc (showString "releases") , doc (showString "=") , prt 0 releaseblocks , doc (showString "}")])



